# Generated by Django 4.0.1 on 2022-04-18 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_profile1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile1',
        ),
    ]
