# Generated by Django 4.0.1 on 2022-04-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_delete_profile1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('review', models.TextField()),
            ],
            options={
                'db_table': 'feedback3',
            },
        ),
    ]
