# Generated by Django 4.0.1 on 2022-04-19 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_feedback3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback2',
        ),
    ]
