# Generated by Django 4.0.1 on 2022-04-19 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_delete_feedback2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback3',
            new_name='Feedback',
        ),
        migrations.AlterModelTable(
            name='feedback',
            table='feedback',
        ),
    ]
