# Generated by Django 4.0.1 on 2022-04-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_rename_feedback3_feedback_alter_feedback_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('contact', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=800)),
                ('inimage', models.ImageField(upload_to='upload/')),
            ],
            options={
                'db_table': 'inquiry1',
            },
        ),
    ]
