# Generated by Django 4.0.1 on 2022-04-19 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_inquiry2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inquiry1',
        ),
    ]
