# Generated by Django 4.0.1 on 2022-04-19 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_delete_inquiry1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inquiry2',
            new_name='Inquiry',
        ),
        migrations.AlterModelTable(
            name='inquiry',
            table='inquiry',
        ),
    ]
