# Generated by Django 4.0.1 on 2022-04-18 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin2', '0002_profile2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
