# Generated by Django 4.0.1 on 2022-04-18 17:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myadmin2', '0003_delete_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile2',
            new_name='Profile',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
